name: streamate_flutter_app
description: A new Flutter project.


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^0.13.5
  injectable: ^1.0.0
  flutter_bloc: ^7.0.0
  get_it: ^7.2.0 
  either_dart: ^0.3.0
  webview_flutter: ^4.0.2
  shared_preferences: ^2.0.17
  dio: ^4.0.6

  web_socket_channel: ^2.3.0

  mocktail: ^0.3.0
  rxdart: ^0.27.7
  #build_runner: ^2.2.0 # For generating code (Mocks, etc)
  #mockito: ^5.2.0 # For mocking and stubbing

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/twitch_icon.svg
    - assets/images/logo_twitch_bw.png
    - assets/images/item_fondo.png
    - assets/images/item_fondo_inferior.png
    - assets/images/modo_sub_activado.png
    - assets/images/modo_sub_desactivado.png
    - assets/images/modo_lento_activado.png
    - assets/images/modo_lento_desactivado.png
    - assets/images/modo_emote_activado.png
    - assets/images/modo_emote_desactivado.png
    - assets/images/modo_seguidores_activado.png
    - assets/images/modo_seguidores_desactivado.png
    - assets/images/anuncios_activado.png
    - assets/images/anuncios_desactivado.png
    - assets/images/reply_icon.png
    - assets/images/sub_tier.png
    - assets/images/prime_logo.png
    - assets/images/sub_gift_icon.png
    - assets/images/anuncio_icono.png
    - assets/images/offline_image_default.jpg

  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand_Regular.ttf
        - asset: assets/fonts/Quicksand_Bold.ttf
          weight: 700
        - asset: assets/fonts/Quicksand_SemiBold.ttf
          weight: 400
        - asset: assets/fonts/Quicksand_Medium.ttf
          weight: 500
        - asset: assets/fonts/Quicksand_Light.ttf
          weight: 400
  #         style: italic
    - family: Roobert
      fonts:
        - asset: assets/fonts/Roobert_Regular.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
